### ISSUE TITLE
Enforce commit conventions locally with `commitizen`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/policy#97]
[ComPWA's commit conventions](https://compwa-org.readthedocs.io/develop.html#commit-conventions) can probably be enforced locally as well with [`commitizen`](https://commitizen-tools.github.io/commitizen). It can also be [used as a pre-commit hook](https://commitizen-tools.github.io/commitizen/#integrating-with-pre-commit) and it can be installed at the commit stage with the new [`default_install_hook_types`](https://pre-commit.com/#top_level-default_install_hook_types).

```yaml
default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
```

It still needs to be found out how to configure the commit types. Probably best to [configure `commitizen` through `pyproject.toml`](https://commitizen-tools.github.io/commitizen/config).

---

Note that commit conventions are already enforced to PR titles with [`commitlint.config.js`](https://github.com/ComPWA/repo-maintenance/blob/545507e73d3c3bdf39250dd94ca5399d1dbffe6f/commitlint.config.js) (see corresponding workflow [here](https://github.com/ComPWA/repo-maintenance/blob/91a7c336517aeb839f763ec2e606bf62eed3bc56/.github/workflows/pr-linting.yml)). It would be nice if this configuration redundancy can be removed somehow.
